package org.firstinspires.ftc.teamcode.usbserial;

public enum CommandType {
    CMD_RESET,
    CMD_SETMOTORPOWER,
    CMD_SETMOTORPOWERS,
    CMD_READENCODER,
    CMD_RESETENCODER,
    CMD_SETMOTORDIRECTION,
    CMD_SETMOTORZEROPOWERBEHAVIOUR,
    CMD_READMOTORCURRENT,
    CMD_SETSERVOPOSITION,
    CMD_READDISTANCE
}
